// <auto-generated />
using FlagAcademy.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlagAcademy.Migrations
{
    [DbContext(typeof(FlagAcademyContext))]
    [Migration("20240130213648_FlagAndCountryModels")]
    partial class FlagAndCountryModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlagAcademy.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlagId")
                        .HasColumnType("integer")
                        .HasColumnName("flag_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("FlagId")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_flag_id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("FlagAcademy.Models.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.HasKey("Id")
                        .HasName("pk_flags");

                    b.ToTable("flags", (string)null);
                });

            modelBuilder.Entity("FlagAcademy.Models.Country", b =>
                {
                    b.HasOne("FlagAcademy.Models.Flag", "Flag")
                        .WithOne("Country")
                        .HasForeignKey("FlagAcademy.Models.Country", "FlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_countries_flags_flag_id");

                    b.Navigation("Flag");
                });

            modelBuilder.Entity("FlagAcademy.Models.Flag", b =>
                {
                    b.Navigation("Country")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
